### ISSUE TITLE
Support for OPML import

### ISSUE THREAD

**Issue by sibeliusg** [strukturart/feedolin#1]
As I have a lot of feeds in my other news readers, inserting all into the json file is a lot of work. Importing them by an .opml file would be much more pleasant

**Comment by strukturart** [comment]
I will try, what is the structure of the opml files?

**Comment by sibeliusg** [comment]
It is in Markup language

Something like this:
https://ufile.io/r2nxt1di

**Comment by strukturart** [comment]
in principle opml would be possible, but I save in the json file how many articles from the feeds should be displayed in the reader. I did it that way because you can quickly change a device and because the user input in the phone is really no fun.

**Comment by sibeliusg** [comment]
I see. Most Feed readers only have a global setting, which defines how many articles per feed are loaded... opml is kind of standard for most news readers. That's why I believe it would be nice and easy to have. For me it would be okay to define globally, how many articles are loaded rather than for each feed individually.

**Comment by strukturart** [comment]
yes that would be a possibility, if the global value set is used, otherwise it was stored in the json file.

**Comment by strukturart** [comment]
https://github.com/strukturart/rss-reader/projects/1

**Comment by strukturart** [comment]
I started to support .opml files,
please do a test by storing the url for your opml in the settings. in order not to write the whole url you can use a qr code. the structure should look like this: https://raw.githubusercontent.com/strukturart/rss-reader/master/example.opml

**Comment by sibeliusg** [comment]
Thank you! The result is a white screen with a black stripe and after some seconds it brings me to the settings of the app. Impossible to close the app now...

`    at <anonymous> (app://{6578cafa-ae8b-423e-8880-0f3cad1293c1}/assets/js/script.js:802:1)`

is all webIDE-console is giving me

Here is the [OPML](https://gist.githubusercontent.com/sibeliusg/746737b1b4bfb4203574ceaa28e86d27/raw/0635fbf83c7932aaf27601eb7768aac2e12e86d4/subscription.opml)

**Comment by strukturart** [comment]
is the opml file stored online or locally ?

Am Do., 20. Mai 2021 um 11:26 Uhr schrieb sibeliusg <
***@***.***>:

**Comment by sibeliusg** [comment]
it's online. I used the link above

**Comment by strukturart** [comment]
Your opml file works for me, did you save it in the correct field in the settings?
have you installed the latest version of the app via webIDE?

**Comment by strukturart** [comment]
updated: support for local opml file

**Comment by sibeliusg** [comment]
I installed the Zip-build. Am I supposed to install via WebIDE? I'll try the latest version

**Comment by sibeliusg** [comment]
Well the new app doesn't load more than the Welcome screen or stays at a white screen. No console output at all. Installed latest git-version with WebIDE

**Comment by strukturart** [comment]
pls try the zip from the pre release:
https://github.com/strukturart/rss-reader/releases/tag/1.8

>
>
>

**Comment by sibeliusg** [comment]
yesss!!! works! Awesome! Thank you for bringing us the best news reader for KaiOS!

**Comment by strukturart** [comment]
Your are welcome! pls share the app and have look to my o.map app: https://github.com/strukturart/o.map

**Comment by sibeliusg** [comment]
Yep! I use o.map for quite some time and love it. Same with Telekram and Bhackers-Store.

**Comment by strukturart** [comment]
I've added a new tab: recently played, if you want to test it....
