### ISSUE TITLE
Nextcloud news support

### ISSUE THREAD

**Issue by sibeliusg** [strukturart/feedolin#2]
another feature request is to let the rss reader sync with nextcloud news

**Comment by strukturart** [comment]
do i use nextcloud news an rss reader plugin?

**Comment by sibeliusg** [comment]
Yes, it's like a self hosted Feedly or Inoreader, which works as a nextcloud plugin. I guest it will be quite some work though

**Comment by strukturart** [comment]
is it possible to export the urls ?

**Comment by sibeliusg** [comment]
Yes as an .opml (But the point of nextcloud news is, to sync articles and read status with many devices...

Here is the API I guess:

https://github.com/nextcloud/news/tree/master/docs/externalapi

**Comment by Kaios3046831** [comment]
Hello Sir,
             I request please make vpn app for kaios devices. Is it possible vpn app for kaios devices

#Contact
vijaymovie786@gmail.com
thanks for reading
