### ISSUE TITLE
Can't open articles 

### ISSUE THREAD

**Issue by sibeliusg** [strukturart/feedolin#3]
As you see in the video. When clicking on an article, it is marked as read, but it won't open.

Edit: [Video now on Youtube](https://youtu.be/rhMB84iW1zg)

**Comment by strukturart** [comment]
how did you install my app and can you send me an rss-feed url so that i can look at its content.

**Comment by sibeliusg** [comment]
I installed with bHacker-Store. 

Here is my [rss.json](https://gist.github.com/sibeliusg/392e32bb151b2fd6f6660ad8e215e931)

**Comment by strukturart** [comment]
I have uploaded the latest version, please try the installation again.

**Comment by sibeliusg** [comment]
Same issue. Also happens with the default json file

**Comment by strukturart** [comment]
hmh strange, can you install the app with the webIDE?
https://github.com/strukturart/rss-reader/tree/master/application

**Comment by sibeliusg** [comment]
Did so. Still no change. Perhaps a device specific bug. I'm on Alcatel 3088X, KaiOS 2.5.1.1

**Comment by strukturart** [comment]
is there a console output from the webide?

**Comment by sibeliusg** [comment]
Hmm, I reinstalled it dirty with WebIDE and now it works. No idea, why.

**Comment by sibeliusg** [comment]
But now the local rss.json file is not recognized, which worked in the previous version. I deleted the default url, put in the local path (/sdcard/rss.json, also tried rss.json, which worked before) in the right field. Still your default news show up, even after a reboot

**Comment by sibeliusg** [comment]
Console output:
`Array [ "-1406873644", "1660989050", "1660989050", "1660989050", "1030108270", "-1374870325", null, "681829136", "-1592761612", "-1679631394", 2 more… ] 
    at <anonymous> (app://a938985d-8066-4cf5-8189-e6e17777a94e/assets/js/script.js:866:1)  
script.js:866:1
`

**Comment by sibeliusg** [comment]
Sorry again! It was because I set download frequency to 30min and so it didn't update, when opening the app.

**Comment by strukturart** [comment]
I fixed the bug, tested it on the nokia8110 GerdaRom
